{% set name = "dockerspawner" %}
{% set version = "12.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b2cf2f4284b71f0bf34bc79c622f54805275167c83b446dfc05d8ee27294d60b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vv .

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - docker-py
    - escapism
    - jupyterhub >=0.4

test:
  imports:
    - dockerspawner

about:
  home: https://github.com/jupyterhub/dockerspawner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Spawns JupyterHub single user servers in Docker containers '

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
    - minrk
