{% set name = "dockerspawner" %}
{% set version = "13.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ce95367d96e4bdc10fefb7dc3c54c7d312a1b383f0e17c1e3978f7ef9f28ada

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - docker-py
    - escapism
    - jupyterhub-base >=2.3.1

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - dockerspawner
  commands:
    - pip check
    

about:
  home: https://github.com/jupyterhub/dockerspawner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Spawns JupyterHub single user servers in Docker containers '

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
    - minrk
