{% set name = "dockerspawner" %}
{% set version = "12.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3894ed8a9157f8ac8f42e0130f43932490ac5d1e89e6f295b1252f08c00ba36b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vv .

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - docker-py
    - escapism
    - jupyterhub >=1.0

test:
  imports:
    - dockerspawner

about:
  home: https://github.com/jupyterhub/dockerspawner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Spawns JupyterHub single user servers in Docker containers '

extra:
  recipe-maintainers:
    - dhirschfeld
    - rzillman
    - minrk
