travis:
  secure:
    BINSTAR_TOKEN: nV7cSIeYm7vTZ4Z6g1PU3UqukKpOdb0VL0l+RuOQMf/HWSDY2P4rD3b5Gf1kEWvPzYNvq3IHsIBAsNpbKgx/wqJLmIJ9FVP5/o5q0c5nHzNTOnxicT0Mrl9tAEM8nKVWG6pKi5LOQU4qzvlDQFu+RyACJaQ1P6WiFq+jqKwy0xz0jHhf+N4/KxQbCh/CyR/Mba79W30qOvmp8kr0SSnwm6MO7pP0BqUdGH7ZP5GTwY1KcXlybeKS+iLvWnfeyWhgx3rAo/exPLEUzMN/UV2WeBE9joVi+P1Dv78ylJNLlU0Nh0wnfG/j4jIRWcZXKgmDDJNb9xVjJj6A6EMwXFfcBgKFGK3O9X+qBEZw//9ON0bM+qyCvEw8CyslHLwqeVZbftGODZ04kgjN6dfd3yFN0+0C4MBwzvNuG5Ih0R491xhc2GPw6S+srWYRNq8n1YRlmQoUtmW3IE+RQj5adWbLMW/6+hMJXd4FuMmgf5p9s17gEjVdFMDC9RtSiB+yFrG4iHDpguWIaUFZICfcGK9MO02Ars7P2OonmYWgg6aInGan1SyG4ac9YuYNETU/RshOVXftgTUXs0woYGM53clf0LbXZ0lsvNMTT+/0PHY3S8MP5Kq6m0Ml+IY7er3tBzYIyg6cBlZv7zAtoqmB1o8oBTb/ANgvPJF/H9YLhH9cb+w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
